services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://api-gateway:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api-gateway

  api-gateway:
    build:
      context: ./backend
      dockerfile: apps/api-gateway/Dockerfile
    container_name: api-gateway
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
      - JWT_SECRET=supersecretkey
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - auth

  auth:
    build:
      context: ./backend
      dockerfile: apps/auth/Dockerfile
    container_name: auth
    ports:
      - "3001:3001"
    env_file:
      - ./backend/apps/auth/.env
    volumes:
      - ./backend:/app
      - /app/node_modules

  event-reservation-service:
    build:
      context: ./backend
      dockerfile: apps/event-reservation-service/Dockerfile
    container_name: reserve-event
    ports:
      - "3002:3002"
    env_file:
      - ./backend/apps/event-reservation-service/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - auth
